#pragma once
#include "animator.h"
#include "autoTile.h"
#include "coordTransform.h"
#include "gameObject.h"
#include "gameplay.h"
#include "map.h"
#include "pointVector.h"
#include "sound.h"
#include "sprite.h"
#include "wndControl.h"
#include "sound.h"

#include <vector>
#include <queue>
#include <map>
#include <fstream>
#include <cmath>
#include <sstream>
#include <ctime>
#include <string>